### ISSUE TITLE
Question on crawls and their licensing

### ISSUE THREAD

**Issue by pdehaye** [InteractiveAdvertisingBureau/adstxtcrawler#22]
The branch `adstxt-results` contains historic crawls of ads.txt s all over the web. 
How was the initial list of domains obtained? The commit message says "Google's ads.txt crawler". 

Also, what is the licensing on this data?

**Comment by nealrichter** [comment]
it's a list of domains to start you off.   Consider it an open source file of domains with ads.txt files.
