### ISSUE TITLE
Missing value for ADSYSTEM_DOMAIN in INSERT 

### ISSUE THREAD

**Issue by AssafNK** [InteractiveAdvertisingBureau/adstxtcrawler#6]
Hi,
In the INSERT query there is no value for ADSYSTEM_DOMAIN which is configured as NOT NULL in adstxt table and the insert is failing.
When creating the table without it all works.

**adstxt_crawler.py line 59**
`insert_stmt = "INSERT OR IGNORE INTO adstxt (SITE_DOMAIN, EXCHANGE_DOMAIN, SELLER_ACCOUNT_ID, ACCOUNT_TYPE, TAG_ID, ENTRY_COMMENT) VALUES (?, ?, ?, ?, ?, ? );"`

**Create Table in adstxt_crawler.sql**
`CREATE TABLE adstxt(
       SITE_DOMAIN                  TEXT    NOT NULL,
       EXCHANGE_DOMAIN              TEXT    NOT NULL,
       ADSYSTEM_DOMAIN		    INTEGER     NOT NULL,
       SELLER_ACCOUNT_ID            TEXT    NOT NULL,
       ACCOUNT_TYPE                 TEXT    NOT NULL,
       TAG_ID                       TEXT    NOT NULL,
       ENTRY_COMMENT                TEXT    NOT NULL,
       UPDATED                      DATE    DEFAULT (datetime('now','localtime')),
    PRIMARY KEY (SITE_DOMAIN,EXCHANGE_DOMAIN,SELLER_ACCOUNT_ID)
);`

**Comment by bradlucas** [comment]
I noticed the same thing and worked around it by commenting out the ADSYSTEM_DOMAIN column in the adstxt_crawler.sql file. Run the reinit.sh script to rebuild your database and you should be good to go.

I seems that there is some work in progress related to that column that hasn't been implemented fully in the code.

**Comment by Kinghaji4040** [comment]
thanks alot

**Comment by nealrichter** [comment]
fixed.
